@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Mar 09 02:07:11 -0700 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim L5_tb_behav -key {Behavioral:sim_1:Functional:L5_tb} -tclbatch L5_tb.tcl -view Z:/dcengr/Desktop/ELEN 122L/Lab 5/Lab_5/L5_tb_behav.wcfg -log simulate.log"
call xsim  L5_tb_behav -key {Behavioral:sim_1:Functional:L5_tb} -tclbatch L5_tb.tcl -view Z:/dcengr/Desktop/ELEN 122L/Lab 5/Lab_5/L5_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
